apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docurag.fullname" . }}-secrets
  labels:
    {{- include "docurag.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}